website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from . import db
from .models import Movies, Venue, Booking
from flask_login import login_required, current_user
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

views = Blueprint('views', __name__)


@views.route('/admin_login_home', methods=['GET', 'POST'])
@login_required
def admin_login_home():
    print(current_user)
    all_movies = Movies.query.all() 
    all_venue = Venue.query.all()
    return render_template("home_admin.html", movies = all_movies, venue = all_venue, admin = current_user)


@views.route('/user_signup_home')
@login_required
def user_signup_home():
    return redirect(url_for("views.user_login_home"))    
 

@views.route('/admin_signup_home', methods=['GET', 'POST'])
@login_required
def admin_signup_home():
    return redirect(url_for("views.admin_login_home"))   


@views.route('/add_movie', methods=['GET', 'POST'])
@login_required
def add_movie():
    if request.method == 'POST':
        m_name = request.form.get("moviename")
        m_venue = request.form.get("venuename")
        m_price = request.form.get("movieprice")
        m_tags = request.form.get("movietags")
        m_capacity = request.form.get("moviecapacity")
        venue = Venue.query.all()
        flag = False
        for v in venue:
            if (v.venue_name == m_venue):
                new_movie = Movies(movie_name = m_name, movie_venue = m_venue, movie_price = m_price, movie_tags = m_tags, movie_capacity = m_capacity)
                db.session.add(new_movie)
                db.session.commit()
                flag = True
        if flag:
            flash("New entry added to Movie Table.")   
        else:
            flash("Entered Venue Name does not exists in Venue Table.")    
        return redirect(url_for('views.add_movie'))

    return render_template("add_movie.html", admin = current_user)


@views.route('/add_venue', methods=['GET', 'POST'])
@login_required
def add_venue():
    if request.method == 'POST':
        v_name = request.form.get("venuename")
        v_place = request.form.get("venueplace")
        v_location = request.form.get("venuelocation")

        new_venue = Venue(venue_name = v_name, venue_place = v_place, venue_location = v_location)
        db.session.add(new_venue)
        db.session.commit()
        flash("New entry added to Venue Table.")
        return redirect(url_for("views.add_venue"))

    return render_template("add_venue.html", admin = current_user)      


@views.route('/delete_movie/<int:id>')
@login_required
def delete_movie(id):
    movie_to_delete = Movies.query.get(id)
    db.session.delete(movie_to_delete)
    db.session.commit()
    return redirect(url_for("views.admin_login_home"))


@views.route('/delete_venue/<int:id>')
@login_required
def delete_venue(id):
    venue_to_delete = Venue.query.get(id)
    movies = Movies.query.all()
    flag = False
    for i in movies:
        if i.movie_venue == venue_to_delete.venue_name:
            db.session.delete(i)
            db.session.delete(venue_to_delete)
            db.session.commit()
            flag = True
    if flag == False:
        db.session.delete(venue_to_delete)
        db.session.commit()        
    return redirect(url_for("views.admin_login_home"))


@views.route('/view_page_movie/<int:id>', methods=['GET', 'POST'])
@login_required
def view_page_movie(id):
    movie_to_view = Movies.query.get(id)
    print(movie_to_view)
    return render_template("update_movie.html", movie_to_view = movie_to_view, admin = current_user)    


@views.route('/update_movie/<int:id>', methods=['GET', 'POST'])
@login_required
def update_movie(id):
    movie_to_update = Movies.query.get(id)
    print(movie_to_update)
    if request.method == 'POST':
        venue = Venue.query.all()
        m_venue = request.form.get("venuename")
        flag = False
        for v in venue:
            if (v.venue_name == m_venue):
                movie_to_update.movie_name = request.form.get('moviename')
                movie_to_update.movie_venue = request.form.get('venuename')
                movie_to_update.movie_price = request.form.get('movieprice')     
                movie_to_update.movie_tags = request.form.get('movietag')
                movie_to_update.movie_capacity = request.form.get('moviecapacity')
                db.session.commit()
                flag = True
        if flag:
            flash("Details updated in Movie Table.")   
        else:
            flash("Entered Venue Name does not exists in Venue Table.")    
        return redirect(url_for('views.admin_login_home', id = id))     


@views.route('/view_page_venue/<int:id>', methods=['GET', 'POST'])
@login_required
def view_page_venue(id):
    venue_to_view = Venue.query.get(id)
    print(venue_to_view)
    return render_template("update_venue.html", venue_to_view = venue_to_view, admin = current_user)    


@views.route('/update_venue/<int:id>', methods=['GET', 'POST'])
@login_required
def update_venue(id):
    venue_to_update = Venue.query.get(id)
    print(venue_to_update)
    if request.method == 'POST':
        print("step 1")
        venue_to_update.venue_name = request.form.get('venuename')
        venue_to_update.venue_place = request.form.get('venueplace')     
        venue_to_update.venue_location = request.form.get('venuelocation')
        db.session.commit()
        flash("Details updated in Venue Table.") 
        return redirect(url_for("views.admin_login_home"))  


@views.route("/search", methods=['GET', 'POST'])
@login_required
def search():
    search = request.form.get("search")
    movie = Movies.query.all()
    venue = Venue.query.all()
    movie_search = {}
    venue_search = {}
    if request.method == 'POST':
        for i in movie:
            print("asd")
            print(i)
            movie_search[i.movie_venue] = []
            print(movie_search)
            if i.movie_name == search:
                print("match")
                movie_search[i.movie_venue].append((i.movie_name, i.movie_id, i.avg_rating_s, i.movie_capacity))
                print(movie_search)
                return render_template("search.html", search_list = movie_search, search = search, user = current_user)  
            else:
                for i in venue:
                    venue_search[i.venue_name] = []
                    if i.venue_name == search or i.venue_location == search or i.venue_place == search:
                        for j in movie:
                            if j.movie_venue == i.venue_name:
                                venue_search[j.movie_venue].append((j.movie_name, j.movie_id, j.avg_rating_s, j.movie_capacity))
                                print(venue_search)
                venue_search_2={}
                for key, value in venue_search.items():
                    if value != []:
                        venue_search_2[key] = value
                print(venue_search_2)   
                print("a")     
                return render_template("search.html", search_list = venue_search_2, search = search, user = current_user)     
        return render_template("search.html", search_list = movie_search, search = search, user = current_user)      
    return ('hellod')

@views.route('/user_login_home', methods=['GET', 'POST'])
@login_required
def user_login_home():
        print(current_user)
        venue = Movies.query.group_by(Movies.movie_venue)
        movie = Movies.query.all()
        dict={}
        for i in venue:
            dict[i.movie_venue]=[]
            for j in movie:
                if i.movie_venue == j.movie_venue:
                    dict[i.movie_venue].append((j.movie_name, j.movie_id, j.avg_rating_s, j.movie_capacity)) 
        recomd=[]
        for i in movie:
            if (i.avg_rating_s >= 4):
                recomd.append(i)      
            
        return render_template("user_home.html", dict = dict, recomd = recomd, user = current_user)
        

@views.route('/booking_page/<int:id>', methods=['GET', 'POST'])
@login_required
def booking_page(id):
    print(id)
    movie = Movies.query.get(id)
    return render_template('booking_page.html', movie = movie, user = current_user)

@views.route('/housefull', methods=['GET', 'POST'])
@login_required
def housefull():
    flash("Sorry, this Show is HOUSEFULL.")
    return redirect(url_for("views.user_login_home"))


@views.route('/booking_page_2/<int:id>', methods=['GET', 'POST'])
@login_required
def booking_page_2(id):
    try: 
        movie = Movies.query.get(id)
        movie_capacity = movie.movie_capacity
        movie_price = movie.movie_price
        print("a")

        if request.method == 'POST':
            print("b")
            seats = request.form.get('seats')
            print(seats)
            if (int(seats) <= int(movie_capacity)):
                cost = int(seats)*int(movie_price)
            return render_template("booking_page_2.html", movie = movie, seats = seats, cost = cost, user = current_user)
    except:
        flash("You have entered seats more than available seats.")  
        return redirect(url_for("views.booking_page", id = id))
    
    
@views.route('/flash_success/<int:seats>/<int:cost>/<int:id>', methods=['GET', 'POST'])
@login_required
def flash_success(seats, cost, id):
    movie = Movies.query.get(id)
    movie_capacity = movie.movie_capacity
    new_capacity = int(movie_capacity)-int(seats)
    movie.movie_capacity = new_capacity
    new_booking = Booking(booking_movie_name = movie.movie_name, booking_venue = movie.movie_venue, booking_seats = seats, booking_cost = cost, booking_user = current_user.user_name)
    db.session.add(new_booking)
    db.session.commit()
    flash("Booking Successfull")
    return render_template("booking_page_2.html", movie = movie, seats = seats, cost = cost, user = current_user)
    

@views.route('/booking_summary', methods=['GET', 'POST'])
@login_required
def booking_summary():

website/templates/home_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Admin Home</title>
</head>
<body style ="background-image: url(https://thumbs.dreamstime.com/b/movie-cinema-icons-vector-illustration-horizontal-flat-design-various-58158312.jpg);">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% for message in get_flashed_messages() %}
      <div class="alert alert alert-dismissible fade show" role="alert" style="margin-top: 20px; width: 1150px; margin-left: 200px; background-image: linear-gradient(90deg, #E7E9BB,  #403B4A);">
        <div style="font-weight: bolder; font-family: papyrus; font-size: large;">{{message}}</div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>      
    {% endfor %}
    <div class="expmouse">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black; border-right: 50px; height: 50px; width: 1140px; margin-left: 200px; margin-top: 55px;">
            <a class="navbar-brand" href="#" style=" font-size:30px; font-family: Brush Script MT;">Ticket Show</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>   
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02" style="font-family: century gothic;">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="http://127.0.0.1:5000/admin_login_home" style="margin-left:50px; font-size: large;">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="http://127.0.0.1:5000/add_movie" style="margin-left:25px; font-size: large;">Insert Movie</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="http://127.0.0.1:5000/add_venue" style="margin-left:25px; font-size: large;">Insert Venue</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" style="font-size: large; margin-left: 350px;">{{admin.admin_name}}</a>
                </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <button class="btn btn-outline-info my-2 my-sm-0 " type="submit" formaction="/logout" formmethod="POST" style="margin-left: 10px">Logout</button>
                </form>
            </div>
        </nav>
        <div class = "container" style="font-family: sans-serif; width: 1150px; height: 555px; margin-top: 10px; margin-left: 200px; background-color: white; opacity: .85;">
            <span>
                <div class="container-movies" style="float:left; height: 530px; width: 525px; margin-top:25px; margin-left:25px; ">
                    <h3 style="padding-left: 140px; font-family: papyrus;"><b>Movies</b></h3>
                    <br>
                    <table style="height:fit-505px; width:525px;">
                        <tr>
                            <th>
                                Movie
                            </th>
                            <th>
                                Venue
                            </th>
                            <th>
                                Price
                            </th>
                            <th>
                                Tags
                            </th>
                            <th>
                                Capacity
                            </th>
                        </tr>
                        {% for i in movies %}
                        <tr>
                            <td>{{i.movie_name}}</td>
                            <td>{{i.movie_venue}}</td>
                            <td>{{i.movie_price}}</td>
                            <td>{{i.movie_tags}}</td>
                            <td>{{i.movie_capacity}}</td>
                            <td style="padding-bottom: 7px;">
                                <div class="btn-group dropright">
                                    <button type="button" class="btn btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 100px; font-size: 15px; font-weight: bold; cursor: pointer; font-family: papyrus;">
                                    Action
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{url_for('views.view_page_movie', id = i.movie_id)}}">Edit</a>
                                        <a class="dropdown-item" href="{{url_for('views.delete_movie', id = i.movie_id)}}">Delete</a>
                                    </div>
                                </div>
                            </td>    
                        </tr>    
                        {% endfor %}
                    </table>
                </div>
            </span> 
            <span>
                <div class="container-movies" style="float:left; height: 530px; width: 525px; margin-top:25px; margin-left:25px; ">
                    <h3 style="padding-left: 140px; font-family: papyrus;"><b>Venues</b></h3>
                    <br>
                    <table style="height:fit-505px; width:525px;">
                        <tr>
                            <th>
                                Venue
                            </th>
                            <th>
                                Place
                            </th>
                            <th>
                                Location
                            </th>
                        </tr>
                        {% for j in venue %}
                        <tr>
                            <td>{{j.venue_name}}</td>
                            <td>{{j.venue_place}}</td>
                            <td>{{j.venue_location}}</td>
                            <td style="padding-bottom: 7px;">
                                <div class="btn-group dropright">
                                    <button type="button" class="btn btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 100px; font-size: 15px; font-weight: bold; cursor: pointer; font-family: papyrus;">
                                    Action
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{url_for('views.view_page_venue', id = j.venue_id)}}">Edit</a>
                                        <a class="dropdown-item" href="{{url_for('views.delete_venue', id = j.venue_id)}}">Delete</a>
                                    </div>
                                </div>
                            </td>    
                        </tr>    
                        {% endfor %}
                    </table>
                </div>
            </span>   
        </div> 
    </div>    
</body>
</html>

website/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body style ="background-image: url(https://thumbs.dreamstime.com/b/movie-cinema-icons-vector-illustration-horizontal-flat-design-various-58158312.jpg)">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black; border-right: 50px; height: 50px; width: 1140px; margin-left: 200px; margin-top: 55px;">
        <a class="navbar-brand" href="#" style=" font-size:30px; font-family: Brush Script MT;">Ticket Show</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>   
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02" style="font-family: century gothic;">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('views.user_login_home')}}" style="margin-left:50px; font-size: large;">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('views.booking_summary')}}" style="margin-left:25px; font-size: large;">View Bookings</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('views.trends')}}" style="margin-left:25px; font-size: large;">Summary</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" style="font-size: large; margin-left: 100px;">{{user.user_name}}</a>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="search" id="search" placeholder="Search">
            <button type="submit" class="btn btn-outline-info my-2 my-sm-0 " formaction="{{url_for('views.search')}}", formmethod="POST">Search</button>
            <button type="button" class="btn btn-outline-info my-2 my-sm-0 " type="submit" style="margin-left: 10px">Logout</button>
            </form>
        </div>
        </nav>
        <!-- <div class = "container" style="font-family: sans-serif; width: 1150px; height: 555px; margin-top: 10px; margin-left: 200px; background-color: black; color: whitesmoke; opacity: .75;">
          <div class="container-content">
            <h3 style="padding-top: 30px; font-family: papyrus;"><b>Results for {{search.venue_name}}</b></h3>
            <div class="movies" style="box-shadow: rgba(0, 0, 0, 0.20) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.20) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.20) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.20) 0px 2px 1px, rgba(0, 0, 0, 0.20) 0px 4px 2px, rgba(0, 0, 0, 0.20) 0px 8px 4px, rgba(0, 0, 0, 0.20) 0px 16px 8px, rgba(0, 0, 0, 0.20) 0px 32px 16px; background-color: whitesmoke; color: black; border-color: aqua; border-width: 5px; border-radius: 20px; width: 150px; height: 100px; float: left; margin-left: 50px; font-family: Copperplate Gothic Light; font-weight: bold; font-size: large;">
                <div align="center" style="margin-top: 40px; margin-bottom: -25px;">
                    {{search}} 
                    <div style="font-size: medium; font-weight: lighter;"></div>
                </div>
                <br>
                <form><button type="submit" class="btn btn-info my-2 my-sm-0 " formaction="" formmethod="POST" style=" margin-left: 45px; height: 30px; width: 100px; border-radius: 5px; cursor: pointer; font-weight: bold; font-family: papyrus;">Book Now</button></form>
            </div>
        </div>  -->
        <!-- </div>  -->
        <div class = "container" style="font-family: sans-serif; width: 1150px; height: 555px; margin-top: 10px; margin-left: 200px; background-color: black; color: whitesmoke; opacity: .75;">
            <div class="container-content">
                <h3 style="padding-top: 30px; font-family: papyrus;"><b>Results for {{search}}</b></h3> 
                <!-- {% if movie_search %}   
                    {% for i in movie_search %}
                    <tr>
                    <div class="movies" style="box-shadow: rgba(0, 0, 0, 0.20) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.20) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.20) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.20) 0px 2px 1px, rgba(0, 0, 0, 0.20) 0px 4px 2px, rgba(0, 0, 0, 0.20) 0px 8px 4px, rgba(0, 0, 0, 0.20) 0px 16px 8px, rgba(0, 0, 0, 0.20) 0px 32px 16px; background-color: whitesmoke; opacity: 1; color: black; border-width: 5px; border-radius: 20px; width: 150px; height: 100px; float: left; margin-left: 50px; margin-top: 100px; font-family: Copperplate Gothic Light; font-weight: bold; font-size: large;">
                        <div align="center" style="margin-top: 40px; margin-bottom: -25px;">
                            {{i[0]}} 
                            <div style="font-size: medium; font-weight: lighter;">/5</div>
                        </div>
                        <br>
                        <form><button type="submit" class="btn btn-info my-2 my-sm-0 " formaction="" formmethod="POST" style=" margin-left: 45px; height: 30px; width: 100px; border-radius: 5px; cursor: pointer; font-weight: bold; font-family: papyrus;">Book Now</button></form>
                    </div>
                    </tr>
                    {% endfor %}
                {% else %}
                    {% for i in venue_search %}
                    <tr>
                    <div class="movies" style="box-shadow: rgba(0, 0, 0, 0.20) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.20) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.20) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.20) 0px 2px 1px, rgba(0, 0, 0, 0.20) 0px 4px 2px, rgba(0, 0, 0, 0.20) 0px 8px 4px, rgba(0, 0, 0, 0.20) 0px 16px 8px, rgba(0, 0, 0, 0.20) 0px 32px 16px; background-color: whitesmoke; opacity: 1; color: black; border-width: 5px; border-radius: 20px; width: 150px; height: 100px; float: left; margin-left: 50px; margin-top: 100px; font-family: Copperplate Gothic Light; font-weight: bold; font-size: large;">
                        <div align="center" style="margin-top: 40px; margin-bottom: -25px;">
                            {{i[0]}}
                            <div style="font-size: medium; font-weight: lighter;">/5</div>
                        </div>
                        <br>
                        <form><button type="submit" class="btn btn-info my-2 my-sm-0 " formaction="" formmethod="POST" style=" margin-left: 45px; height: 30px; width: 100px; border-radius: 5px; cursor: pointer; font-weight: bold; font-family: papyrus;">Book Now</button></form>
                    </div>
                    </tr>
                    {% endfor %}
                {% endif %}     -->


                <!-- {% if movie_search %}
                {% for i in movie_search %}
                <tr>
                    <div class="venue" style="margin-top: 60px; margin-bottom: 60px; margin-left: 100px; height: 100px; width: 1140px; border-radius: 10px;">
                        <h3 style="margin-left: 20px; padding-top: 20px; font-family: papyrus; color: whitesmoke;"><b>{{i}}</b></h3>
                        {% for x in movie_search[i] %}
                            <div class="movies" style="box-shadow: rgba(0, 0, 0, 0.20) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.20) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.20) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.20) 0px 2px 1px, rgba(0, 0, 0, 0.20) 0px 4px 2px, rgba(0, 0, 0, 0.20) 0px 8px 4px, rgba(0, 0, 0, 0.20) 0px 16px 8px, rgba(0, 0, 0, 0.20) 0px 32px 16px; background-color: whitesmoke; color: black; border-width: 5px; border-radius: 20px; width: 150px; height: 100px; float: left; margin-left: 50px; font-family: Copperplate Gothic Light; font-weight: bold; font-size: large;">
                                <div align="center" style="margin-top: 40px; margin-bottom: -25px;">
                                    {{x[0]}} 
                                    <div style="font-size: medium; font-weight: lighter;">{{x[2]}}/5</div>
                                </div>
                                <br>
                                <form><button type="submit" class="btn btn-info my-2 my-sm-0 " formaction="{{url_for('views.booking_page', id = x[1])}}" formmethod="POST" style=" margin-left: 45px; height: 30px; width: 100px; border-radius: 5px; cursor: pointer; font-weight: bold; font-family: papyrus;">Book Now</button></form>
                            </div>
                        {% endfor %}
                    </div>
                </tr>
                {% endfor %}
                {% else %} -->
                {% for i in search_list %}
                <tr>
                    <div class="venue" style="margin-top: 60px; margin-bottom: 60px; margin-left: 100px; height: 100px; width: 1140px; border-radius: 10px;">
                        <h3 style="margin-left: 20px; padding-top: 20px; font-family: papyrus; color: whitesmoke;"><b>{{i}}</b></h3>
                        {% for x in search_list[i] %}
                            <div class="movies" style="box-shadow: rgba(0, 0, 0, 0.20) 0px -23px 25px 0px inset, rgba(0, 0, 0, 0.20) 0px -36px 30px 0px inset, rgba(0, 0, 0, 0.20) 0px -79px 40px 0px inset, rgba(0, 0, 0, 0.20) 0px 2px 1px, rgba(0, 0, 0, 0.20) 0px 4px 2px, rgba(0, 0, 0, 0.20) 0px 8px 4px, rgba(0, 0, 0, 0.20) 0px 16px 8px, rgba(0, 0, 0, 0.20) 0px 32px 16px; background-color: whitesmoke; color: black; border-width: 5px; border-radius: 20px; width: 150px; height: 100px; float: left; margin-left: 50px; font-family: Copperplate Gothic Light; font-weight: bold; font-size: large;">
                                <div align="center" style="margin-top: 40px; margin-bottom: -25px;">
                                    {{x[0]}} 
                                    <div style="font-size: medium; font-weight: lighter;">{{x[2]}}/5</div>
                                </div>
                                <br>
                                {% if x[3] > 0 %}
                                <form><button type="submit" class="btn btn-info my-2 my-sm-0 " formaction="{{url_for('views.booking_page', id = x[1])}}" formmethod="POST" style=" margin-left: 45px; height: 30px; width: 100px; border-radius: 5px; cursor: pointer; font-weight: bold; font-family: papyrus;">Book Now</button></form>
                                {% else %}
                                <form><button type="submit" class="btn btn-info my-2 my-sm-0 " formaction="{{url_for('views.housefull', id = x[1])}}" formmethod="POST" style=" margin-left: 45px; height: 30px; width: 100px; border-radius: 5px; cursor: pointer; font-weight: bold; font-family: papyrus;">Book Now</button></form>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </tr>
                {% endfor %}
                <!-- {% endif %} -->
            </div>    
    </div>    
</body>
</body>
</html>